# Generated by Django 6.0.7 on 2026-08-04 03:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dòng mô hình')),
                ('country', models.CharField(choices=[('JP', 'Nhật Bản'), ('KR', 'Hàn Quốc'), ('OTHER', 'Khác')], default='JP', max_length=20, verbose_name='Quốc gia')),
            ],
            options={
                'verbose_name': 'Hãng',
                'verbose_name_plural': 'Hãng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mô hình')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá (VNĐ)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brand', verbose_name='Hãng')),
            ],
            options={
                'verbose_name': 'Mô hình',
                'verbose_name_plural': 'Mô hình',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm 10 chữ số và bắt đầu bằng số 0 (VD: 0912345678).', regex='^0\\d{9}$')], verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('spam', 'Spam - Đã ẩn')], default='new', max_length=10, verbose_name='Trạng thái')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Mô hình muốn mua')),
            ],
            options={
                'verbose_name': 'Yêu cầu đặt hàng',
                'verbose_name_plural': 'Yêu cầu đặt hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày bán')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá bán thực tế (VNĐ)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Mô hình đã bán')),
            ],
            options={
                'verbose_name': 'Doanh thu',
                'verbose_name_plural': 'Doanh thu',
                'ordering': ['-date'],
            },
        ),
    ]
