# Generated by Django 6.0.7 on 2026-08-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_brand_country_alter_brand_name_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Video ngắn (giới thiệu, 20-30s)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(choices=[('JP', 'Nhật Bản'), ('KR', 'Hàn Quốc'), ('US', 'Mỹ'), ('HK', 'HongKong')], default='JP', max_length=20, verbose_name='Quốc gia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh đại diện'),
        ),
    ]
