# Generated by Django 6.0.7 on 2026-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_video_alter_brand_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Đã bán'),
        ),
    ]
